# Generated by Django 5.1.4 on 2024-12-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SchoolData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_year", models.CharField(max_length=7)),
                ("agency_type", models.CharField(max_length=50)),
                ("cesa", models.CharField(max_length=10)),
                ("county", models.CharField(max_length=50)),
                ("district_code", models.CharField(max_length=10)),
                ("school_code", models.CharField(max_length=10)),
                ("grade_group", models.CharField(max_length=50)),
                ("charter_ind", models.CharField(max_length=4)),
                ("district_name", models.CharField(max_length=100)),
                ("school_name", models.CharField(max_length=100)),
                ("group_by", models.CharField(max_length=50)),
                ("group_by_value", models.CharField(max_length=200)),
                ("student_count", models.CharField(max_length=20)),
                ("percent_of_group", models.CharField(max_length=20)),
            ],
        ),
    ]
