# Generated by Django 5.1.4 on 2024-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schooldata",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
