# Generated by Django 5.1.4 on 2024-12-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0003_transformedschooldata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transformedschooldata",
            old_name="school_year",
            new_name="year",
        ),
        migrations.RenameField(
            model_name="transformedschooldata",
            old_name="agency_type",
            new_name="year_range",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="cesa",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="charter_ind",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="county",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="district_code",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="district_name",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="grade_group",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="percent_of_group",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="school_code",
        ),
        migrations.RemoveField(
            model_name="transformedschooldata",
            name="school_name",
        ),
    ]
