# Generated by Django 5.1.4 on 2024-12-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "__data_processor__",
            "0004_rename_school_year_transformedschooldata_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transformedschooldata",
            options={"ordering": ["year"]},
        ),
    ]
