# Generated by Django 5.1.4 on 2024-12-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0005_alter_transformedschooldata_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetopioTriCountyLayerTransformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(default="Region", max_length=50)),
                ("geoid", models.CharField(default="fox-valley", max_length=50)),
                ("topic", models.CharField(default="FVDEYLCV", max_length=50)),
                ("stratification", models.TextField(blank=True)),
                ("period", models.CharField(max_length=20)),
                ("value", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Metopio Data Transformation",
                "verbose_name_plural": "Metopio Data Transformations",
            },
        ),
        migrations.CreateModel(
            name="Stratification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_by", models.CharField(default="Default Group", max_length=100)),
                (
                    "group_by_value",
                    models.CharField(default="Default Group", max_length=200),
                ),
                (
                    "label_name",
                    models.CharField(default="Default Group", max_length=200),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schooldata",
            name="stratification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="__data_processor__.stratification",
            ),
        ),
    ]
