# Generated by Django 5.1.4 on 2024-12-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "__data_processor__",
            "0006_metopiodatatransformation_stratification_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stratification",
            name="description",
        ),
        migrations.AddField(
            model_name="stratification",
            name="group_by",
            field=models.CharField(default="Default Group", max_length=100),
        ),
        migrations.AddField(
            model_name="stratification",
            name="group_by_value",
            field=models.CharField(default="Default Group", max_length=200),
        ),
        migrations.AlterField(
            model_name="stratification",
            name="label_name",
            field=models.CharField(default="Default Group", max_length=200),
        ),
    ]
