# Generated by Django 5.1.4 on 2024-12-17 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "__data_processor__",
            "0006_metopiotricountylayertransformation_stratification_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metopiotricountylayertransformation",
            options={
                "ordering": ["period", "stratification"],
                "verbose_name": "Metopio Data Transformation",
                "verbose_name_plural": "Metopio Data Transformations",
            },
        ),
    ]
