# Generated by Django 5.1.4 on 2024-12-20 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "__data_processor__",
            "0007_alter_metopiotricountylayertransformation_options",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CountyGEOID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("geoid", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="schooldata",
            name="geoid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="__data_processor__.countygeoid",
            ),
        ),
        migrations.CreateModel(
            name="CountyLayerTransformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(default="County", max_length=50)),
                ("topic", models.CharField(default="FVDEYLCV", max_length=50)),
                ("stratification", models.TextField(blank=True)),
                ("period", models.CharField(max_length=20)),
                ("value", models.PositiveIntegerField()),
                (
                    "geoid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="__data_processor__.countygeoid",
                    ),
                ),
            ],
            options={
                "verbose_name": "County Layer Transformation",
                "verbose_name_plural": "County Layer Transformations",
                "ordering": ["period", "stratification"],
            },
        ),
    ]
