# Generated by Django 5.1.4 on 2024-12-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0008_countygeoid_schooldata_geoid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countylayertransformation",
            name="geoid",
            field=models.CharField(max_length=50),
        ),
    ]
