# Generated by Django 5.1.4 on 2024-12-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0009_alter_countylayertransformation_geoid"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetopioStateWideLayerTransformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(default="State", max_length=50)),
                ("geoid", models.CharField(default="WI", max_length=50)),
                ("topic", models.CharField(default="FVDEYLCV", max_length=50)),
                ("stratification", models.TextField(blank=True)),
                ("period", models.CharField(max_length=20)),
                ("value", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Metopio Statewide Data Transformation",
                "verbose_name_plural": "Metopio Statewide Data Transformations",
                "ordering": ["period", "stratification"],
            },
        ),
    ]
