# Generated by Django 5.1.4 on 2024-12-21 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0010_metopiostatewidelayertransformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolAddressFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lea_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="LEA Code"
                    ),
                ),
                (
                    "district_name",
                    models.CharField(max_length=255, verbose_name="District Name"),
                ),
                (
                    "school_code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="School Code"
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=255, verbose_name="School Name"),
                ),
                (
                    "organization_type",
                    models.CharField(max_length=100, verbose_name="Organization Type"),
                ),
                (
                    "school_type",
                    models.CharField(max_length=100, verbose_name="School Type"),
                ),
                (
                    "low_grade",
                    models.CharField(max_length=10, verbose_name="Low Grade"),
                ),
                (
                    "high_grade",
                    models.CharField(max_length=10, verbose_name="High Grade"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=2, verbose_name="State")),
                ("zip_code", models.CharField(max_length=10, verbose_name="Zip")),
                ("cesa", models.CharField(max_length=10, verbose_name="CESA")),
                ("locale", models.CharField(max_length=100, verbose_name="Locale")),
                ("county", models.CharField(max_length=100, verbose_name="County")),
                (
                    "current_status",
                    models.CharField(max_length=50, verbose_name="Current Status"),
                ),
                (
                    "categories_and_programs",
                    models.TextField(
                        blank=True, null=True, verbose_name="Categories And Programs"
                    ),
                ),
                (
                    "virtual_school",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Virtual School",
                    ),
                ),
                (
                    "ib_program",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IB Program"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number"),
                ),
                (
                    "fax_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Fax Number"
                    ),
                ),
                ("charter_status", models.BooleanField(verbose_name="Charter Status")),
                (
                    "website_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Website URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ZipCodeLayerTransformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(default="County", max_length=50)),
                ("geoid", models.CharField(max_length=50)),
                ("topic", models.CharField(default="FVDEYLCV", max_length=50)),
                ("stratification", models.TextField(blank=True)),
                ("period", models.CharField(max_length=20)),
                ("value", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "County Layer Transformation",
                "verbose_name_plural": "County Layer Transformations",
                "ordering": ["period", "stratification"],
            },
        ),
        migrations.AddField(
            model_name="schooldata",
            name="address_details",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_address_details",
                to="__data_processor__.schooladdressfile",
                verbose_name="Address Details",
            ),
        ),
    ]
