# Generated by Django 5.1.4 on 2024-12-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "__data_processor__",
            "0011_schooladdressfile_zipcodelayertransformation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooladdressfile",
            name="lea_code",
            field=models.CharField(max_length=10, verbose_name="LEA Code"),
        ),
        migrations.AlterField(
            model_name="schooladdressfile",
            name="school_code",
            field=models.CharField(max_length=10, verbose_name="School Code"),
        ),
    ]
