# Generated by Django 5.1.4 on 2024-12-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0012_alter_schooladdressfile_lea_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schooldata",
            name="address_details",
        ),
        migrations.AddField(
            model_name="schooldata",
            name="address_details",
            field=models.ManyToManyField(
                blank=True,
                related_name="school_data",
                to="__data_processor__.schooladdressfile",
                verbose_name="Address Details",
            ),
        ),
    ]
