# Generated by Django 5.1.4 on 2024-12-23 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0013_remove_schooldata_address_details_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zipcodelayertransformation",
            options={
                "ordering": ["period", "geoid", "stratification"],
                "verbose_name": "County Layer Transformation",
                "verbose_name_plural": "County Layer Transformations",
            },
        ),
    ]
