# Generated by Django 5.1.4 on 2024-12-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0014_alter_zipcodelayertransformation_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetopioCityLayerTransformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(default="City", max_length=50)),
                ("geoid", models.CharField(max_length=50)),
                ("topic", models.CharField(default="FVDEYLCV", max_length=50)),
                ("stratification", models.TextField(blank=True)),
                ("period", models.CharField(max_length=20)),
                ("value", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "City Layer Transformation",
                "verbose_name_plural": "City Layer Transformations",
                "ordering": ["period"],
            },
        ),
    ]
