# Generated by Django 5.1.4 on 2025-01-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0016_metopiocensustractlayertransformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metopiocensustractlayertransformation",
            name="geoid",
            field=models.CharField(max_length=100),
        ),
    ]
