# Generated by Django 5.1.4 on 2025-02-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "__data_processor__",
            "0017_alter_metopiocensustractlayertransformation_geoid",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetopioCensusTractLayerTransformation",
        ),
    ]
