# Generated by Django 5.1.4 on 2025-02-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0018_delete_metopiocensustractlayertransformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stratification",
            name="label_name",
            field=models.CharField(
                blank=True, default="Default Group", max_length=200, null=True
            ),
        ),
    ]
