# Generated by Django 5.1.4 on 2025-02-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0019_alter_stratification_label_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stratification",
            name="label_name",
            field=models.CharField(default="Default Group", max_length=200),
        ),
    ]
