# Generated by Django 5.1.4 on 2025-02-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0020_alter_stratification_label_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schooldata",
            name="address_details",
        ),
    ]
